version: '3.4'

services:
  dockerthing:
    image: dockerthing
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 3069:3069
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "app.js"]
