CREATE DATABASE IF NOT EXISTS dev;
USE dev;
CREATE TABLE recordedVotes (
`voteID` INT NOT NULL AUTO_INCREMENT ,
`votedNum` INT NOT NULL ,
`vote` BOOLEAN NOT NULL ,
`voteTime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
PRIMARY KEY (`voteID`)
);